CREATE TABLE IF NOT EXISTS houses(--カラム名
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,--ID
name VARCHAR(50) NOT NULL,--民宿名
image_name VARCHAR(255),--民宿画像のファイル名
description VARCHAR(255) NOT NULL,--民宿の説明
price INT NOT NULL,--一泊当たりの宿泊料金
capacity INT NOT NULL,--定員
postal_code VARCHAR(50) NOT NULL,--郵便番号
address VARCHAR(255) NOT NULL,--住所
phone_number VARCHAR(50) NOT NULL,--電話番号
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,--作成日時
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP--更新日時
);

CREATE TABLE IF NOT EXISTS roles(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
furigana VARCHAR(50) NOT NULL,
postal_code VARCHAR(50) NOT NULL,
address VARCHAR(255) NOT NULL,
phone_number VARCHAR(50) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role_id INT NOT NULL,
enabled BOOLEAN NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS verification_tokens(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL UNIQUE,
token VARCHAR(255) NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS reservations (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
house_id INT NOT NULL,
user_id INT NOT NULL,
checkin_date DATE NOT NULL,
checkout_date DATE NOT NULL,
number_of_people INT NOT NULL,
amount INT NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (house_id) REFERENCES houses (id),
FOREIGN KEY (user_id) REFERENCES users (id)
);